name: Release
on:
  create:
    tags:
      - v*

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{secrets.ADDRESS}}
          server_port: 465
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          subject: ${{github.repository}}
          body: ${{matrix.body}}
          to: ${{github.event.pusher.email}}
          from: github-actions
          content_type: ${{matrix.content_type}}
          attachments: ${{matrix.attachments}}		      
       - name: Validates GO releaser config
         uses: docker://goreleaser/goreleaser:latest
         with:
          args: check
      - name: Create release on GitHub
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
